[2023-01-28 01:04:32,140] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2023-01-28 01:04:32,153] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2023-01-28 01:04:32,154] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-28 01:04:32,155] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-01-28 01:04:32,156] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-28 01:04:32,176] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-04-01 00:00:00+00:00
[2023-01-28 01:04:32,184] {standard_task_runner.py:52} INFO - Started process 1803 to run task
[2023-01-28 01:04:32,189] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpm9quw5ln', '--error-file', '/tmp/tmpfknxnz08']
[2023-01-28 01:04:32,191] {standard_task_runner.py:77} INFO - Job 83: Subtask local_to_gcs_task
[2023-01-28 01:04:32,260] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-04-01T00:00:00+00:00 [running]> on host adbf820de9e6
[2023-01-28 01:04:32,307] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-28 01:04:32,327] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-01T00:00:00+00:00
[2023-01-28 01:07:02,302] {python.py:175} INFO - Done. Returned value was: None
[2023-01-28 01:07:02,314] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20190401T000000, start_date=20230128T010432, end_date=20230128T010702
[2023-01-28 01:07:02,339] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-01-28 01:07:02,371] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-01-29 12:42:07,389] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2023-01-29 12:42:07,400] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2023-01-29 12:42:07,401] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:42:07,402] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-01-29 12:42:07,403] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:42:07,413] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-04-01 00:00:00+00:00
[2023-01-29 12:42:07,420] {standard_task_runner.py:52} INFO - Started process 6652 to run task
[2023-01-29 12:42:07,423] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '389', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpddv71ec0', '--error-file', '/tmp/tmpis5zw843']
[2023-01-29 12:42:07,424] {standard_task_runner.py:77} INFO - Job 389: Subtask local_to_gcs_task
[2023-01-29 12:42:07,494] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-04-01T00:00:00+00:00 [running]> on host 2530f37057aa
[2023-01-29 12:42:07,542] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-29 12:42:07,563] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-01T00:00:00+00:00
[2023-01-29 12:42:18,697] {python.py:175} INFO - Done. Returned value was: None
[2023-01-29 12:42:18,711] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20190401T000000, start_date=20230129T124207, end_date=20230129T124218
[2023-01-29 12:42:18,754] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-01-29 12:42:18,793] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
