[2023-01-28 01:07:37,428] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-08-01T00:00:00+00:00 [queued]>
[2023-01-28 01:07:37,438] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-08-01T00:00:00+00:00 [queued]>
[2023-01-28 01:07:37,439] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-28 01:07:37,440] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-01-28 01:07:37,441] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-28 01:07:37,452] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-08-01 00:00:00+00:00
[2023-01-28 01:07:37,457] {standard_task_runner.py:52} INFO - Started process 2230 to run task
[2023-01-28 01:07:37,461] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-08-01T00:00:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp9n8bjfda', '--error-file', '/tmp/tmpm9c8_1rq']
[2023-01-28 01:07:37,462] {standard_task_runner.py:77} INFO - Job 93: Subtask local_to_gcs_task
[2023-01-28 01:07:37,523] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-08-01T00:00:00+00:00 [running]> on host adbf820de9e6
[2023-01-28 01:07:37,565] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-28 01:07:37,585] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-08-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-08-01T00:00:00+00:00
[2023-01-28 01:09:35,672] {python.py:175} INFO - Done. Returned value was: None
[2023-01-28 01:09:35,689] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20190801T000000, start_date=20230128T010737, end_date=20230128T010935
[2023-01-28 01:09:35,717] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-01-28 01:09:35,748] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-01-29 12:45:22,123] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-08-01T00:00:00+00:00 [queued]>
[2023-01-29 12:45:22,133] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-08-01T00:00:00+00:00 [queued]>
[2023-01-29 12:45:22,134] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:45:22,135] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-01-29 12:45:22,136] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:45:22,146] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-08-01 00:00:00+00:00
[2023-01-29 12:45:22,151] {standard_task_runner.py:52} INFO - Started process 7386 to run task
[2023-01-29 12:45:22,155] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-08-01T00:00:00+00:00', '--job-id', '413', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmprj8f2483', '--error-file', '/tmp/tmpinn_qsoc']
[2023-01-29 12:45:22,156] {standard_task_runner.py:77} INFO - Job 413: Subtask local_to_gcs_task
[2023-01-29 12:45:22,213] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-08-01T00:00:00+00:00 [running]> on host 2530f37057aa
[2023-01-29 12:45:22,260] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-29 12:45:22,282] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-08-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-08-01T00:00:00+00:00
[2023-01-29 12:45:33,344] {python.py:175} INFO - Done. Returned value was: None
[2023-01-29 12:45:33,360] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20190801T000000, start_date=20230129T124522, end_date=20230129T124533
[2023-01-29 12:45:33,426] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-01-29 12:45:33,469] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
