[2023-01-28 01:09:33,598] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-09-01T00:00:00+00:00 [queued]>
[2023-01-28 01:09:33,609] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-09-01T00:00:00+00:00 [queued]>
[2023-01-28 01:09:33,610] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-28 01:09:33,611] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-01-28 01:09:33,612] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-28 01:09:33,622] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-09-01 00:00:00+00:00
[2023-01-28 01:09:33,627] {standard_task_runner.py:52} INFO - Started process 2476 to run task
[2023-01-28 01:09:33,630] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-09-01T00:00:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpja8l1_pj', '--error-file', '/tmp/tmpfoquv0xn']
[2023-01-28 01:09:33,631] {standard_task_runner.py:77} INFO - Job 96: Subtask local_to_gcs_task
[2023-01-28 01:09:33,690] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-09-01T00:00:00+00:00 [running]> on host adbf820de9e6
[2023-01-28 01:09:33,734] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-28 01:09:33,753] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-01T00:00:00+00:00
[2023-01-28 01:11:57,104] {python.py:175} INFO - Done. Returned value was: None
[2023-01-28 01:11:57,115] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20190901T000000, start_date=20230128T010933, end_date=20230128T011157
[2023-01-28 01:11:57,157] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-01-28 01:11:57,189] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-01-29 12:45:46,044] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-09-01T00:00:00+00:00 [queued]>
[2023-01-29 12:45:46,054] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-09-01T00:00:00+00:00 [queued]>
[2023-01-29 12:45:46,055] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:45:46,056] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-01-29 12:45:46,056] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:45:46,068] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-09-01 00:00:00+00:00
[2023-01-29 12:45:46,073] {standard_task_runner.py:52} INFO - Started process 7504 to run task
[2023-01-29 12:45:46,076] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-09-01T00:00:00+00:00', '--job-id', '417', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp8ag_d6vc', '--error-file', '/tmp/tmpk2_f5zmx']
[2023-01-29 12:45:46,077] {standard_task_runner.py:77} INFO - Job 417: Subtask local_to_gcs_task
[2023-01-29 12:45:46,136] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-09-01T00:00:00+00:00 [running]> on host 2530f37057aa
[2023-01-29 12:45:46,182] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-29 12:45:46,204] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-01T00:00:00+00:00
[2023-01-29 12:46:03,733] {python.py:175} INFO - Done. Returned value was: None
[2023-01-29 12:46:03,749] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20190901T000000, start_date=20230129T124546, end_date=20230129T124603
[2023-01-29 12:46:03,778] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-01-29 12:46:03,809] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
