[2023-01-28 01:10:03,010] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2023-01-28 01:10:03,020] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2023-01-28 01:10:03,021] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-28 01:10:03,022] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-01-28 01:10:03,022] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-28 01:10:03,033] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-11-01 00:00:00+00:00
[2023-01-28 01:10:03,038] {standard_task_runner.py:52} INFO - Started process 2573 to run task
[2023-01-28 01:10:03,042] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-11-01T00:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp_uvbrg46', '--error-file', '/tmp/tmplezhcbr4']
[2023-01-28 01:10:03,043] {standard_task_runner.py:77} INFO - Job 101: Subtask local_to_gcs_task
[2023-01-28 01:10:03,112] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-11-01T00:00:00+00:00 [running]> on host adbf820de9e6
[2023-01-28 01:10:03,163] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-28 01:10:03,188] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-11-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-11-01T00:00:00+00:00
[2023-01-28 01:12:00,063] {python.py:175} INFO - Done. Returned value was: None
[2023-01-28 01:12:00,078] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20191101T000000, start_date=20230128T011003, end_date=20230128T011200
[2023-01-28 01:12:00,112] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-01-28 01:12:00,141] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-01-29 12:46:50,673] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2023-01-29 12:46:50,687] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2023-01-29 12:46:50,688] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:46:50,689] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-01-29 12:46:50,689] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:46:50,702] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-11-01 00:00:00+00:00
[2023-01-29 12:46:50,708] {standard_task_runner.py:52} INFO - Started process 7736 to run task
[2023-01-29 12:46:50,712] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-11-01T00:00:00+00:00', '--job-id', '425', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpgmhe0182', '--error-file', '/tmp/tmp1r6jw38p']
[2023-01-29 12:46:50,714] {standard_task_runner.py:77} INFO - Job 425: Subtask local_to_gcs_task
[2023-01-29 12:46:50,781] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-11-01T00:00:00+00:00 [running]> on host 2530f37057aa
[2023-01-29 12:46:50,832] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-29 12:46:50,869] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-11-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-11-01T00:00:00+00:00
[2023-01-29 12:47:04,059] {python.py:175} INFO - Done. Returned value was: None
[2023-01-29 12:47:04,075] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20191101T000000, start_date=20230129T124650, end_date=20230129T124704
[2023-01-29 12:47:04,138] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-01-29 12:47:04,176] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
